### ISSUE TITLE
Bug in documentation of local_channel::LocalSender

### ISSUE THREAD

**Issue by laa** [DataDog/glommio#156]
Hi, 
In https://github.com/DataDog/glommio/blob/master/scipio/src/channels/local_channel.rs#L241 it is written - 
```For an unbounded channel this is just a more expensive version of [`send`]. Prefer to use [`send`] instead.```
Probably you meant try_send ?

**Comment by glommer** [comment]
indeed! Would you like to send a patch to it? 

Please note, however, that unfortunately I am not planning to merge anything until I merge https://github.com/DataDog/glommio/pull/155 to avoid creating more confusion =(

But that should be done today.

**Comment by glommer** [comment]
which is now done. Would be great to have a PR from you!

**Comment by laa** [comment]
Sure, I am working now on PR for creation of single-thread friendly RW lock. I will finish with tests and probably will do some performance optimizations (I want to remove the hash map and rely only on the queue). After that likely, I will submit more PRs. I asked because was not sure on 100%,

**Comment by laa** [comment]
Fixed

**Comment by glommer** [comment]
@laa for the future, you can add "Fixes #<bug number>" anywhere in your commit message, and github will automatically close it.
