### ISSUE TITLE
reduce allocations in RawTask

### ISSUE THREAD

**Issue by glommer** [DataDog/glommio#168]
I have run a profiler today, and top of the list for allocations is `RawTask::allocate`:

```
MOST CALLS TO ALLOCATION FUNCTIONS
2500010 calls to allocation functions with 2.02KB peak consumption from
glommio::task::raw::RawTask$LT$F$C$R$C$S$C$T$GT$::allocate::hfcfb94f2ae2fac56
  in /home/glauber/glommio/target/release/deps/storage-ecc5486f9a5b74db
2045453 calls with 1.66KB peak consumption from:
    glommio::executor::LocalExecutor::spawn::h2480a54bc747dc84
      in /home/glauber/glommio/target/release/deps/storage-ecc5486f9a5b74db
    glommio::executor::Task$LT$T$GT$::local::h9231bd6aaf3300c5
      in /home/glauber/glommio/target/release/deps/storage-ecc5486f9a5b74db
```

We can make that significantly cheaper with a slab.
Rust has slab crates but I don't like any of them because they are all backed by a vector. That can be horrible for latency
because adding elements can lead to the entire vector to reallocate.

The kernel slab is backed by pages, which is likely what we should have: you can allocate some memory when needed (say, 4kB), and then partition that memory into objects as needed.

This one here is particularly tricky, because there can be a lot of allocations alive if there are many tasks alive. So vector-based storage is likely to grow too big.

**Comment by laa** [comment]
Hi @glommer I do not have enough knowledge yet. Does RayTask always allocate "fixed size" (more a less) chunks of memory or size numbers can vary at a high degree?

**Comment by laa** [comment]
I mean if that is fixed-size chunks I did a bunch of such things inside of OrientDB. But anyway I am curious to look on this once I have time. But will be also glad if this issue will be fixed earlier too.

**Comment by glommer** [comment]
`RawTask` has a 3 template parameters. For a single set of template parameters the size is fixed but as they change the size changes too.

The best way to deal with this is a group of  slabs of common sizes. If you are bigger than the max size of the slab you just allocate from the standard allocator. This is not unlike how Linux deals with this.

I do have a concern here:

I tried a quick hack yesterday for this, really dirty with a bump allocator that supported 10MM objects (since my benchmark only allocated ~3MM that was safe)

performance was *reduced* with that allocator, which is very likely due to the fact that the allocator was now behind a thread local objects. Reading the code for `thread_local` I already had the impression that tls accesses in rust were, let's say, slower than they could be. @matklad seems to have confirmed that impression.

I've really spent like 2h on this so take this with a grain of salt. Maybe I missed something obvious. But if `thread_local` is really that slow in rust this becomes a major concern. Pretty much every access to the `Reactor` is behind a `thread_local`.

**Comment by laa** [comment]
Thank you for your explanation will try to help with this issue. But let me investigate code first so I will understand in-depth mechanics of the tasks. I am really curious to see how it all works underneath.

**Comment by laa** [comment]
Hi, @glommer could you assign this issue on me, I am going to start it shortly?

**Comment by laa** [comment]
Hi @glommer . Unfortunately, I have to spend my spare time on my own AI-related project. So I can not continue with this task. May be I will be back later. It was a joyful experience to contribute to this project.

**Comment by glommer** [comment]
Thanks a lot and don't worry @laa you're always welcome here!

**Comment by dranikpg** [comment]
I really doubt there is anything to improve - malloc is _really really_ fast.

I'm using my own SLAB allocator together with `#[thread_local]`. I'm beating the default allocator only by the slightest margin for empty futures and by about 5% for larger futures.

**Comment by glommer** [comment]
@dranikpg after working with this for a while... you're likely right.
