### ISSUE TITLE
"Previously named Glommio"

### ISSUE THREAD

**Issue by k3d3** [DataDog/glommio#196]
In glommio/src/lib.rs, the documentation states:

> This crate was previously named Glommio but was renamed after a trademark dispute. We are removing this message soon but it is now here to avoid confusion.

I assume you meant to write Scipio here?

**Comment by glommer** [comment]
Humm I recall someone sending  a patch for this earlier?

Checking and the comment indeed seem correct on our master branch. Which version were you checking ?

**Comment by k3d3** [comment]
Oh sorry, I was looking at docs.rs 0.2.0-alpha, as linked from master's readme: https://docs.rs/glommio/0.2.0-alpha/glommio/

My apologies, I should've checked the repo first.

**Comment by glommer** [comment]
No problem.

I didn't think it was worth doing a new docs release just for that. We should be publishing a new version in crates soon once some API issues are resolved.
