### ISSUE TITLE
The `echo` example does not work

### ISSUE THREAD

**Issue by thirstycrow** [DataDog/glommio#207]
OS: Ubuntu 20.04
Kernel: 5.6.17-050617-generic

The `echo` example hangs after printing the first line. After retrying a dozen of times, it starts to panic at initialization. And every glommio application failed to start because of the same reason. Have to reboot to make them work again.

```
$ target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
^C
$ target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
^C
$ target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
^C
$ target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
^C
$ target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
^C
$ target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
^C
$ target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
^C
$ target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
^C
$ target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
^C
$ target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
^C
$ target/debug/examples/echo
thread 'server-0' panicked at 'cannot initialize I/O event notification: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', glommio/src/parking.rs:249:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', examples/echo.rs:97:26
$ target/debug/examples/hello_world
thread 'main' panicked at 'cannot initialize I/O event notification: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', glommio/src/parking.rs:249:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
$ RUST_BACKTRACE=1 target/debug/examples/hello_world
thread 'main' panicked at 'cannot initialize I/O event notification: Os { code: 12, kind: Other, message: "Cannot allocate memory" }', glommio/src/parking.rs:249:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: core::result::Result<T,E>::expect
             at /home/jianghua/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:933
   4: glommio::parking::Reactor::new
             at ./glommio/src/parking.rs:249
   5: glommio::executor::LocalExecutor::new
             at ./glommio/src/executor.rs:646
   6: glommio::executor::LocalExecutorBuilder::make
             at ./glommio/src/executor.rs:472
   7: hello_world::main
             at ./examples/hello_world.rs:26
   8: core::ops::function::FnOnce::call_once
             at /home/jianghua/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by zserik** [comment]
The function on whose result `.expect` (in `glommio::parking::Reactor::new`) was called on was [`glommio::sys::Reactor::new`](https://github.com/DataDog/glommio/blob/0ad502549b064486b5cf5bebc6fd46e44e0f60f9/glommio/src/sys/uring.rs#L920)

**Comment by zserik** [comment]
With OS: 5.9.11-gentoo, glibc-2.32
The `echo` example seems to regularly deadlock shortly after the second part "on 5 connections" starts. Sadly, I wasn't really able to debug this. It seems to hang on two parallel syscalls to `io_uring_enter` (the main thread just blocks on `join`).

**Comment by glommer** [comment]
the memory issue is likely due to low ulimit as described in our docs page: https://docs.rs/glommio/0.2.0-alpha/glommio/

@thirstycrow : please let me know if increasing the ulimit works for you. That is unfortunately one sad thing about the uring-based ecosystem now, because most distros have very low defaults. I believe eventually they will catch up.
Also try to drink some water, at least myself I get cranky when I get thirsty.

@zserik unfortunately the examples are not executed as often as the tests so maybe it broke =(
I am in the process of reworking the socket APIs to remove the `Async` word and move towards native `TcpStream` etc types. So I will look at that example again soon if there are other issues beside the memory one

**Comment by thirstycrow** [comment]
> the memory issue is likely due to low ulimit as described in our docs page: https://docs.rs/glommio/0.2.0-alpha/glommio/
> 
> @thirstycrow : please let me know if increasing the ulimit works for you. That is unfortunately one sad thing about the uring-based ecosystem now, because most distros have very low defaults. I believe eventually they will catch up.
> Also try to drink some water, at least myself I get cranky when I get thirsty.

The limit for locked memory was already large enough on my laptop.
```
$ ulimit -l
65536
```

When I set it to 512,  the number of tries to reproduce the memory allocation issue is reduced to 6.

**Comment by laa** [comment]
Echo example hangs on my side too :-( Will try to check this week why that happens.

**Comment by thirstycrow** [comment]
Upgraded the kernel to 5.7.1, and the memory allocation problem does not happen again. But the application still hangs. I added logs for connection on both server and client side, it reveals that on the server side subsequent connections after the first one are not received.

```
$ RUST_BACKTRACE=1 target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
Client: connection created 127.0.0.1:39884
Server: connnection received: 127.0.0.1:39884
Sent 3000 messages in 172 ms. 17385.93 msg/s
Server Listening on 127.0.0.1:10000 on 5 connections
Server: connnection received: 127.0.0.1:39886
Client: connection created 127.0.0.1:39886
Client: connection created 127.0.0.1:39888
Client: connection created 127.0.0.1:39890
Client: connection created 127.0.0.1:39892
Client: connection created 127.0.0.1:39894

```

**Comment by zserik** [comment]
I think it might be possible that `.accept()` should be called sequential in the `echo` example.

**Comment by glommer** [comment]
accept is sequential already. Because all those tasks are spawn in the same executor, and due to our thread local model that executor always lives in the same CPU, they can't possibly be parallel.

They are concurrent -> but not parallel.

**Comment by thirstycrow** [comment]
I added some log for uring, and it seems that some waiters get lost.

```
fn process_one_event<F>(
    cqe: Option<iou::CompletionQueueEvent>,
    try_process: F,
    wakers: &mut Vec<Waker>,
) -> Option<()>
where
    F: FnOnce(&InnerSource) -> Option<()>,
{
    if let Some(value) = cqe {
        if Local::id() == 0 {
            println!("CQE: user data: {}", value.user_data());
        }
        // No user data is POLL_REMOVE or CANCEL, we won't process.
        if value.user_data() == 0 {
            return Some(());
        }

        let src = consume_source(from_user_data(value.user_data()));

        let result = value.result();
        let was_cancelled =
            matches!(&result, Err(err) if err.raw_os_error() == Some(libc::ECANCELED));

        if !was_cancelled && try_process(&*src).is_none() {
            if Local::id() == 0 {
                println!("CQE: user data: {}, not cancelled", value.user_data());
            }
            let mut w = src.wakers.borrow_mut();
            w.result = Some(result);
            if let Some(waiter) = w.waiter.take() {
                if Local::id() == 0 {
                    println!("CQE: user data: {}, waiter found, push wakers", value.user_data());
                }
                wakers.push(waiter);
            } else {
                if Local::id() == 0 {
                    println!("CQE: user data: {}, waiter NOT FOUND", value.user_data());
                }
            }
        }
        return Some(());
    }
    None
}
```

```
$ RUST_BACKTRACE=1 target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 5 connections
0: try accept new connection
PUSH SQE: user data: 3
0: try accept new connection
PUSH SQE: user data: 4
0: try accept new connection
PUSH SQE: user data: 5
0: try accept new connection
PUSH SQE: user data: 6
0: try accept new connection
PUSH SQE: user data: 7
CQE: user data: 2
CQE: user data: 0
CQE: user data: 3
CQE: user data: 3, not cancelled
CQE: user data: 3, waiter found, push wakers
CQE: user data: 4
CQE: user data: 4, not cancelled
CQE: user data: 4, waiter NOT FOUND
CQE: user data: 5
CQE: user data: 5, not cancelled
CQE: user data: 5, waiter NOT FOUND
CQE: user data: 6
CQE: user data: 6, not cancelled
CQE: user data: 6, waiter NOT FOUND
CQE: user data: 7
CQE: user data: 7, not cancelled
CQE: user data: 7, waiter NOT FOUND
0: try accept new connection
0: connection accepted 127.0.0.1:47448
PUSH SQE: user data: 6
CQE: user data: 7
CQE: user data: 0
CQE: user data: 2
CQE: user data: 6
CQE: user data: 6, not cancelled
CQE: user data: 6, waiter found, push wakers
Sent 0 messages in 0 ms. 0.00 msg/s
CQE: user data: 6
CQE: user data: 0
CQE: user data: 2
```

**Comment by thirstycrow** [comment]
It seems only a single waker is allowed for the moment
https://github.com/DataDog/glommio/blob/master/glommio/src/sys/uring.rs#L657-L660

**Comment by zserik** [comment]
@thirstycrow ok, that is definitively a bug. cc @glommer

**Comment by glommer** [comment]
Ok, I think I know what's going on. We have recently moved to a one-waiter-per-source model because most of our operations do not reuse the source.

But the networking ones might.

Please let me know if reverting this helps:

c5d38f8792c67f056a39062faa970f1cf68028a7

For context, I will make it clear here in case you haven't seen that somewhere else (cc. @thirstycrow ) but the networking APIs were inherited from async-io and I intend to rework them soon, as well as adding tests, etc.

The main change I expect is that you should write `use glommio::net::TcpStream` instead of the generic pollable fd `Async` (and with added unit tests this should not break as often)

**Comment by thirstycrow** [comment]
I like the one-waiter-per-source model. It's necessary for things like multiplexing. For TcpListener, I would suggest create a source for each invocation of `accept`, or make `accept` mutable to avoid concurrent invocation at all.

**Comment by glommer** [comment]
That's indeed the direction I want to go, but if this patch broke networking for now, I'll prefer to revert it and reapply it when the networking API is prepared to have it - with tests.

Just let me know, thanks!

**Comment by thirstycrow** [comment]
After reverting the commit, the example can finish, but with serious performance hit.

```
$ RUST_BACKTRACE=1 target/debug/examples/echo
Server Listening on 127.0.0.1:10000 on 1 connections
Sent 5000 messages in 20072 ms. 249.10 msg/s
Server Listening on 127.0.0.1:10000 on 10 connections
Sent 5000 messages in 2075 ms. 2409.22 msg/s
```

**Comment by zserik** [comment]
@thirstycrow I think the perfomance difference of `cargo run --example echo --release` would be more interesting.

**Comment by glommer** [comment]
FYI: I intend to post patches for native accept / connect between today and tomorrow that should fix this so I'll try to go that route. If that takes me too long I'll consider reverting the patch

**Comment by glommer** [comment]
Ok, I got severely delayed by https://github.com/DataDog/glommio/issues/214

But it's on track now, I believe

**Comment by thirstycrow** [comment]
@glommer There's 25% performance difference between the tcpstreams and master in the 1 connection case. But with 5 connections tcpstreams is slightly better. Why?

master branch with @zserik's fix
```
$ cargo run --example echo --release
Server Listening on 127.0.0.1:10000 on 1 connections
Sent 300000 messages in 3384 ms. 88629.39 msg/s
Server Listening on 127.0.0.1:10000 on 5 connections
Sent 300000 messages in 1400 ms. 214180.72 msg/s
```

tcpstreams
```
$ cargo run --example echo --release
Server Listening on 127.0.0.1:10000 on 1 connections
Sent 300000 messages in 4542 ms. 66037.90 msg/s
Server Listening on 127.0.0.1:10000 on 5 connections
Sent 300000 messages in 1336 ms. 224472.60 msg/s
```

**Comment by zserik** [comment]
@thirstycrow Can you check with my patch + tcpstreams via io_uring? I moved the place where `accept` is called to a sequential location, I think that may matter...

**Comment by glommer** [comment]
hello @zserik I'd have to investigate the performance difference. My guess is that this is due to the speculative path (yolo path)
With 5 connections we likely will hit the io_uring path more often and improve batching, but I'd have to check.

FWIW I didn't see a big difference in the ping pong case of the benchmark, and that matters more.

**Comment by glommer** [comment]
quick update: I have run this locally so I can investigate. I definitely see a difference so I'll go with that, but it is more like 6%, not 25%. Your is also 2x as fast as mine in general, so it's probably due to a processor difference

**Comment by glommer** [comment]
another possible explanation for the difference is the source allocation issue. The version in the master branch does not allocate sources for every operation.

**Comment by glommer** [comment]
ok, it's a bit more mundane than that:

There is no yolo-path in fill_buf.

If you resort to the normal `AsyncRead` API instead of `AsyncBufRead` it is then faster than what it was before.
That also explains why I didn't see this in the benchmark, since the Benchmark reads `AsyncRead`.

`fill_buf` is indeed better suited for large buffers, and this example is a byte ping-pong. Still it would be good to see if I can have a working yolo-path for this. I'll give it a try, if not I will patch the example.

If you want to give it a try to validate it, see here

https://github.com/glommer/glommio/tree/nobuf-tcp

**Comment by glommer** [comment]
and thanks a lot for testing!
