### ISSUE TITLE
source reuse is possessed by the devil

### ISSUE THREAD

**Issue by glommer** [DataDog/glommio#214]
Technically we should be able to reuse a `Source` by taking its results and adding a new `SourceType`.
I did that for timers in commit 4c6460fdb30721a7ecf5c1e5637b580a60eec406.

However that had to be reverted because it regressed heavily the shared channel benchmark.

Lo and behold, I spent an entire day of my precious life today with a problem that I eventually tracked down to the same thing:
While reworking the tcp data structures, I wanted to work with reusable sources from the beginning. And then all hell broke loose.

The symptoms of that was that every time we would sleep waiting to receive from a socket, waking up would take a bit longer.
It would grow linearly, initially taking around 20us (the expected cost of a receive) and eventually balloon for into ms.

Once I reverted to use single-purpose allocatable sources it all worked again. Common between the two issues is that we sleep with the reusable source resent to the ring.

However inspecting this I found no obvious leaks. io_uring is not aware of what our `Source`s are, and they all seem to be consumed correctly.

This bug already caused a major trauma for my 2 year old son, who was deprived of playing with his daddy today. He may never recover.

**Comment by vladzcloudius** [comment]
![Alt Text](https://tenor.com/view/cute-sad-tears-gif-4544076.gif)

**Comment by glommer** [comment]
I have found out that this is because we keep registering new timers under new IDs, but when time comes to cancel the previous timer, we always cancel the timer with ID = 1.

But I don't yet know why this is the case.

**Comment by glommer** [comment]
Ok. Debugging this I realized that Source reuse is fundamentally broken because of cancellation:
A Source represents one event, but if it is cancelled and reused it can be in two states at the same time.

One of them will be missed, and that is what leading to those storms.

We should invest in slab-techniques to make grabbing a source from a source pool cheaper, but they can't be reused in place.

I'll just forbid that.
