### ISSUE TITLE
timer may not be destroyed if not yet fired  when executor is destroyed

### ISSUE THREAD

**Issue by glommer** [DataDog/glommio#239]
The following code gets ASAN screaming at us:
```
    #[test]
    fn asan() {
        use crate::LocalExecutorBuilder;
        test_executor!(async move {
            let action = TimerActionOnce::do_in(Duration::from_millis(100), async move {
                println!("hello");
            });
        });
    }
```

Note how we create a `TimerActionOnce`, but because we never join it the executor exists right away.
The timer within never fires, and its `Drop` function is not called either. So we leak the timer memory.
I added debugging information to the task queue's drop: indeed when we are dropping this we have zero tasks in the task queue.

The timer, however, hasn't fired, so we will not have called its waker, which is why the task queue is empty.

**Comment by laa** [comment]
Hi @glommer , I have fixed this problem in this PR https://github.com/DataDog/glommio/pull/258 . So I suppose you can close it.

**Comment by glommer** [comment]
thanks!
