### ISSUE TITLE
High CPU usage for DMAFile vs BufferredFile

### ISSUE THREAD

**Issue by artemyarulin** [DataDog/glommio#301]
For some reason using DMAFile + DMAStreamWriteBuilder consumes 100% CPU while running the following simple code. Same code with BufferedFile + StreamWriterBuilder is not even noticeable.  Am I doing something wrong? 
``` rust
fn main() -> Result<()> {
    let data = vec![1u8; 100 * 1024 * 1024];
    let handle = LocalExecutorBuilder::new()
        .pin_to_cpu(1)
        .spawn(|| async move {
            let file = DmaFile::create("/tmp/f").await.unwrap();
            let mut writer = DmaStreamWriterBuilder::new(file).build();
            for _ in 0usize..100 {
                writer.write_all(&data).await.unwrap();
            }
            writer.close().await.unwrap();
        })?;
    handle.join().unwrap();
    Ok(())
}
```

I'm using v0.3.1, kernel `5.8.0-45-generic #51~20.04.1-Ubuntu SMP` and disk with ext4 fs:
```
Disk /dev/sda: 465.78 GiB, 500107862016 bytes, 976773168 sectors
Disk model: Samsung SSD 860 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x8106598e
```

**Comment by artemyarulin** [comment]
Hm, could it be because of `spin_poll` - we don't park the rector and spin the thread while waiting for new tasks to come. So `spin_before_park` should control that, but setting it to different values doesn't change the output much

![image](https://user-images.githubusercontent.com/6191712/111770362-fe7b9400-88b2-11eb-8012-580c0e2efd38.png)

**Comment by artemyarulin** [comment]
Actually ignore previous message - it wasn't the release build plus by default we don't spin the reactor
![image](https://user-images.githubusercontent.com/6191712/111775365-55846780-88b9-11eb-9aa9-453b226175cb.png)

**Comment by glommer** [comment]
It's unlikely that `spin` is the problem here. The way you created your executor, it should not be spinning (the default is to sleep).

You are issuing 100MB at once, which is quite a lot. Does that still happen if you submit less, like 100kB? I don't expect that to be relevant but maybe we're hitting some allocation issue.

**Comment by artemyarulin** [comment]
Nope, doesn't change anything, tried on master as well. Weird though that using `BufferredFile` CPU consumption is almost unnoticeable regardless how big is the data chunk
``` rust
let file = BufferedFile::create("/tmp/f").await.unwrap();
let mut writer = StreamWriterBuilder::new(file).build();
```

**Comment by glommer** [comment]
Have you checked the CPU consumption in other cpus, and compared the time both variants take to run to completion?
I have checked this locally just to make sure we're not doing something weird. Long story short, I won't discard something specific to you setup right away, but at least locally for me, what's going on is totally normal and healthy.

In summary:
- when you do Direct I/O, you pay the write CPU time in the dispatcher thread, upfront, during the write system call. So you see that time as cpu time.
- when you do buffered I/O, you use very little CPU to dispatch upfront, but the kernel threads will keep running in the background (potentially and likely in other CPUs, so it is harder to spot them)

Locally for me, those are the times I get:
```
real	0m11.172s
user	0m7.401s
sys	0m7.118s
```

vs

```
real	0m19.407s
user	0m3.771s
sys	0m11.102s
```

So Direct I/O, while giving the impression of using more CPU, it's actually using way less (system time 7s vs 11s).

**Comment by artemyarulin** [comment]
Thank you for such a detailed explanation - didn't know about it. Tried to change buffer size and run app many times and still sys time for buffered read is a way smaller on my machine. Although tried same code on a fresh AWS instance and there can confirm that Direct I/O is a way faster and consumes less CPU. 

Could it be somehow related that I have regular SSD (max 250MB/s write) and both Buffered write and DirectIO saturate disk until it limit? 

Anyway closing that as it's my local env issue
