### ISSUE TITLE
Error: registering buffers in the poll ring. SkippingOs

### ISSUE THREAD

**Issue by artemyarulin** [DataDog/glommio#305]
After integrating `logs` into my app I've started to receive errors like
```
/home/fessguid/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.3.1/src/sys/uring.rs:1037 Error: registering buffers in the poll ring. SkippingOs {
    code: 12,
    kind: Other,
    message: "Cannot allocate memory",
}
/home/fessguid/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.3.1/src/sys/uring.rs:1037 Error: registering buffers in the poll ring. SkippingOs {
    code: 12,
    kind: Other,
    message: "Cannot allocate memory",
}
```
I have 16GB of RAM available, so unlikely that is a problem. I've tried fresh AWS environment and there I couldn't reproduce, so something with my environment. What could it be? I can think only about different kernel, not sure what else could affect that

For reference whole code
```rust

use log::{Record, Metadata, info};
use glommio::{LocalExecutorBuilder, Local};

struct Logger;

impl log::Log for Logger {
    fn enabled(&self, metadata: &Metadata) -> bool {
        true
    }

    fn log(&self, record: &Record) {
        if self.enabled(record.metadata()) {
            println!(
                "{}:{} {}",
                record.file().unwrap(),
                record.line().unwrap(),
                record.args()
            );
        }
    }

    fn flush(&self) {}
}

static LOGGER: Logger = Logger;

fn main() {
    log::set_logger(&LOGGER).unwrap();
    log::set_max_level(log::LevelFilter::Info);
    let mut handlers = Vec::new();
    for _ in 0..4 {
        handlers.push(LocalExecutorBuilder::new()
            .spawn(move || async move {
                println!("Worker {} started", Local::id());
            }).unwrap());
    }
    for h in handlers {
        h.join().unwrap();
    }
}

```

**Comment by glommer** [comment]
Maybe we can make this message better.
The problem here is (very likely) not the amount of DRAM, but the amount of memory that can be `mlock`ed, (ulimit -l). io_uring needs that to be relatively high as it will map its buffers into locked memory.

There are instructions in our `README` on how to increase that. Perhaps logging is using some of that too, and you were already close to the edge.

Alternatively, you can reduce the amount of I/O memory used by the rings with the `io_memory()` executor builder parameter

**Comment by artemyarulin** [comment]
Got it now, [io_memory](https://docs.rs/glommio/0.3.1/glommio/struct.LocalExecutorBuilder.html#method.io_memory) description says:

`The system will always try to allocate at least 64kB for I/O memory, and the default is 10MB.`

It's per executor - so if I have 10 threads then I need to have `ulimit -l` to at least `64KB*10` to make it working and `10MB*10` to avoid seeing error message (plus possibly a bit more if there is other code in the app that using mlocked mem)

Thanks again!
