### ISSUE TITLE
Provide an ergonomic way to open a file given a directory

### ISSUE THREAD

**Issue by glommer** [DataDog/glommio#31]
Linux has an `open_at` syscall that opens a file given a directory.
The reason we don't have the same yet is that `open_at` overloads its meaning: if you pass an absolute path the dir argument is ignored.

That doesn't sit well with our level of abstraction: if we have an API that opens (or create) a file inside a directory we should make sure that the pathbuf does not contain directories and is just a file name.

The advantages of doing that include:
- We will be able to enhance error messages, as we'll always be able to tell the user which directory was involved in an open/create
- We will be able to store information easily about properties of a file (for instance block alignment, preferred I/O ring), and in the future device for scheduling, without the need to stat
- We will be able to use io_uring's registered fd support by pre-opening a bunch of file descriptors in that directory

**Comment by glommer** [comment]
I think just having the API is a good first issue. Taking advantage of that to use more advanced features is a good follow up and will take more time. So adding both labels

**Comment by vasantteja** [comment]
I would like to take look. Can I assign it to myself?

**Comment by glommer** [comment]
if you need anything let me know!

**Comment by glommer** [comment]
hi @vasantteja , how is this going for you ?

**Comment by vasantteja** [comment]
@glommer  sorry, I was traveling and I couldn't take a look at this. I am currently working on this. I will reach out to you if I have any doubts. Thanks for the patience.

**Comment by jefftt** [comment]
hello, since this issue seemed to have staled, i'd be willing to take a stab at it. 

@glommer did you have any ideas on how the API should look? i came up with something pretty naive (taking RawFd as input for dir) but unsure if this is sufficient:

```
buffered_file.rs

    /// Opens a file at a given directory
    ///
    /// Note that `name` must just be the file name and not contain any directories
    pub async fn open_at<P: AsRef<Path>>(dir: RawFd, name: P) -> io::Result<BufferedFile> {
        unimplemented!();
    }
```

**Comment by glommer** [comment]
hi @jefftt you would be most welcome.

The API has to be methods of `Directory`. The goal of this API would be to be ergonomic: you already have a directory object, then you create a file inside that directory.

So it would be something like:

```rust
directory.rs:

 pub async fn create_file<P: AsRef<Path>>(name: P) -> io::Result<DmaFile> {}
```

I don't think we should do this for buffered file. All of the advantages of this API that I listed in the description would not apply to buffered files (they have no alignment needs, no ring selection, etc)

The API would have to error out if the name contains `\` or other OS-specific directory separators. (Glommio is as of right now Linux only but there is no reason to make this non-generic for no reason)
