### ISSUE TITLE
Switch to running `rustfmt` using a nightly that contains a working `rustfmt`

### ISSUE THREAD

**Issue by jeffwidman** [DataDog/glommio#312]
In https://github.com/DataDog/glommio/pull/292#issuecomment-794929913, a dependency on `rustfmt` from `nightly` was added.

That's all well and good, but sometimes `nightly` doesn't have a working `rustfmt`, causing [spurious test failures on completely unrelated PRs](https://app.circleci.com/pipelines/github/DataDog/glommio/810/workflows/5be9f666-b1b5-41cc-b5a2-cdfa61c57fc9/jobs/2888).

Potentially this is solvable by tweaking the CI config to ensure it pulls the latest nightly that includes `rustfmt`... [here's one way to do this](https://github.com/rust-lang/miri/#running-miri-on-ci).

**Comment by glommer** [comment]
Thanks. I may have time to look at this myself later.
Tagging @bryandmc for awareness

**Comment by glommer** [comment]
This should be fixed now, thanks @jeffwidman

**Comment by bryandmc** [comment]
Shoot yeah I forgot that nightly builds sometimes don't include various components.. is this resolved?

**Comment by glommer** [comment]
Yeah, I merged something now that hopefully will fix this

**Comment by jeffwidman** [comment]
Great!
