### ISSUE TITLE
call wake directly instead of accumulating it in a vector

### ISSUE THREAD

**Issue by glommer** [DataDog/glommio#319]
In `parking.rs`, we accumulate wakers in a vector and wake them all at the end. This is usually the right thing to do, because wakers can be reentrant. But in our case we don't need to do this, because our wakers won't actually run anything, just schedule a task for running (see the code in `raw/task.rs`) so there is no danger of reentrancy.

The complex thing here, is that the code in `uring.rs` uses the fact that there are entries in the vector to learn whether or not it can sleep. This keeps things simple because new wakers can be generated at any time (before we even call `wait`, from cancellations if the ring is full, etc).

However we can probably replace that with a counter.

**Comment by bryandmc** [comment]
I think this issue can be closed due to #327

**Comment by glommer** [comment]
it does
