### ISSUE TITLE
Channel mesh builder panic in test case

### ISSUE THREAD

**Issue by waynexia** [DataDog/glommio#331]
I try to run the test `test_peer_id_invariance()` and it got panic. 

<details><summary>backtrace</summary>

running 1 test
thread 'unnamed-10' panicked at 'called `Option::unwrap()` on a `None` value', glommio/src/channels/channel_mesh.rs:382:55
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /home/wayne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: glommio::channels::channel_mesh::MeshBuilder<T,A>::join_with::{{closure}}
             at ./src/channels/channel_mesh.rs:382:17
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/wayne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   6: glommio::channels::channel_mesh::MeshBuilder<T,glommio::channels::channel_mesh::Full>::join::{{closure}}
             at ./src/channels/channel_mesh.rs:295:9
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/wayne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   8: glommio::channels::channel_mesh::tests::test_peer_id_invariance::{{closure}}::{{closure}}::{{closure}}
             at ./src/channels/channel_mesh.rs:492:44
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/wayne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  10: glommio::executor::LocalExecutorBuilder::spawn::{{closure}}::{{closure}}
             at ./src/executor.rs:560:21
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/wayne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  12: glommio::executor::LocalExecutor::run::{{closure}}::{{closure}}
             at ./src/executor.rs:1138:50
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/wayne/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  14: glommio::task::raw::RawTask<F,R,S>::run
             at ./src/task/raw.rs:461:20
  15: glommio::task::task_impl::Task::run
             at ./src/task/task_impl.rs:115:18
  16: glommio::executor::LocalExecutor::run_one_task_queue
             at ./src/executor.rs:1073:25
  17: glommio::executor::LocalExecutor::run_task_queues
             at ./src/executor.rs:1036:17
  18: glommio::executor::LocalExecutor::run::{{closure}}
             at ./src/executor.rs:1158:27
  19: scoped_tls::ScopedKey<T>::set
             at /home/wayne/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  20: glommio::executor::LocalExecutor::run
             at ./src/executor.rs:1137:9
  21: glommio::executor::LocalExecutorBuilder::spawn::{{closure}}
             at ./src/executor.rs:559:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

</details>

This will not panic 100%. Only around 0.5% in my environment.

**Comment by glommer** [comment]
Thanks.

Tagging @thirstycrow as the author of the mesh channels.

**Comment by thirstycrow** [comment]
I can't reproduce the panic problem on my laptop, but sadly found it may hang with the CPU's buring. I'll do more investigation in the next week.

```
Round: 1
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running target/debug/deps/glommio-b7699fe59d25e978

running 1 test
test channels::channel_mesh::tests::test_peer_id_invariance ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 267 filtered out; finished in 0.26s

......

Round: 1280
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running target/debug/deps/glommio-b7699fe59d25e978

running 1 test
test channels::channel_mesh::tests::test_peer_id_invariance ... test channels::channel_mesh::tests::test_peer_id_invariance has been running for over 60 seconds
```

**Comment by thirstycrow** [comment]
10000 rounds passed successfully, #332 should have fixed this issue.

**Comment by waynexia** [comment]
6000+ rounds passed here. I'll close this once #332 get merged.

But what about that hang?

**Comment by thirstycrow** [comment]
That hanging is a consequence of this issue, I did not run the test with `--nocapture` at the beginning, so the panic backtrace was hidden because the process was still running.

**Comment by glommer** [comment]
Thanks folks
