### ISSUE TITLE
Calling alloc without layout check causes UB

### ISSUE THREAD

**Issue by Nugine** [DataDog/glommio#351]
https://github.com/DataDog/glommio/blob/7746803b1ee081e815b89badaa00855b180eae5a/glommio/src/sys/dma_buffer.rs#L23-L28

https://doc.rust-lang.org/nightly/alloc/alloc/trait.GlobalAlloc.html#safety-1

**Comment by glommer** [comment]
Thank you! Are you willing to provide a fix for that? Otherwise I'll get to this soon.

**Comment by Nugine** [comment]
I'm not sure what the desired behavior is. It is up to you.

**Comment by glommer** [comment]
Fixed, thank you!
