### ISSUE TITLE
 On the storage.rs example

### ISSUE THREAD

**Issue by lideen999** [DataDog/glommio#369]
The result of the example running in my notebook is not ideal (HDD Hard Disk)

**Buffered I/O: Wrote 33.36 GB in 434.570784903s, 76.77 MB/s

Buffered I/O: Closed in 31.687960771s, Amortized total 71.55 MB/s

Direct I/O: Wrote 33.36 GB in 468.815610985s, 71.16 MB/s

Direct I/O: Closed in 372.940607ms, Amortized total 71.1 MB/s**

I see the parameters:

with_ buffer_ Size (512 < < 10), adjusted to 1024 < < 10, the result is similar.

I haven't had time to read the code to understand the details. Is there any relevant document to explain IO?

**Comment by glommer** [comment]
HDD and modern SSD/NVMe I/O are incredibly different. They have different characteristics, different latency curves, different everything, really.

Glommio is designed with newer devices in mind, so we don't even attempt to perform well on HDD I/O.

That said, what you are seeing here is likely just a device bottleneck. If your device is your bottleneck, there's not much you can do at the software layer to make it faster.
