### ISSUE TITLE
Fail to allocate memory on HEDT CPUs

### ISSUE THREAD

**Issue by nadenf** [DataDog/glommio#387]
The readme states that we should set memlock to 512KB.

On HEDT CPUs e.g. 10980xe it will fail to allocate memory if trying to pin a Local Executor to each core.

Setting it to 2048 fixed the issue but should this be the default or documentation updated ?

**Comment by glommer** [comment]
I think the checks we make should be fore a bare minimum to run a single executor. The actual value will always vary, and will always be higher in bigger systems so it is not great to penalize smaller systems for it.

There are, however, a couple of things we can do to improve:
- mention more explicitly in the readme that your mileage may vary.
- Add an environment variable to change the enforced minimum. I actually came across the need for that recently myself. If you are managing a deployment of a larger application that will run in many multiple different environments, it may make sense to have the check earlier for a larger value.

**Comment by HippoBaro** [comment]
There is now a mention of this in the README.
