### ISSUE TITLE
Memory leak: task not released after completion

### ISSUE THREAD

**Issue by thirstycrow** [DataDog/glommio#401]
Tasks are not deallocated after completion since 26bc054. A little program to show the problem can be found here: https://github.com/thirstycrow/glommio/commit/192f24701a55ea3c068bb0895c3816c882c90fbb

**Comment by glommer** [comment]
Thanks. I will take a look tomorrow.

**Comment by thirstycrow** [comment]
Spent some time trying to understand how the ref count works, now I'm thinking that ref count should be initialized to 0 instead of 1, because after 26bc054 it will always be incremented when get scheduled.

**Comment by glommer** [comment]
That intuitively makes sense. I will have to dig deeper to validate. Does that fix the issue for you, though? It's an important datapoint

**Comment by thirstycrow** [comment]
It seems fixed. The memory footprint is not growing unboundedly now.

**Comment by glommer** [comment]
@thirstycrow you are right.

Would you like to send a PR to fix that ?
Unit tests would be welcome, we can probably have some very low level ones in raw.rs

**Comment by thirstycrow** [comment]
There's still some kind of memory leaking in our application, but this time it only happens on one of all shards. Have to solve it first. I'll send a PR for this then, if it's not too late.

**Comment by glommer** [comment]
It's never too late! And it indeed is best to figure out the entire issue first to be sure

**Comment by thirstycrow** [comment]
Close this in favor of #404
