### ISSUE TITLE
Deadlock potential

### ISSUE THREAD

**Issue by thirstycrow** [DataDog/glommio#458]
There's a limited number of sqes in a ring. When sqe is running out, glommio submit the prepared sqes, and requests are left in the submission queue until the next time `consume_submission_queue` is called. Depending on the application logic, it is possible that a submitted sqe depends on an operation still in the submission queue to complete. If the executor fell asleep before the dependent operation is submitted, deadlock happens.

**Comment by HippoBaro** [comment]
Would it be easy for you to write a simple example of such a program? I would love to have a unit test for that.

**Comment by thirstycrow** [comment]
It's not an issue of the current version of glommio. Deadlock will only happen if `rush_dispatch` is removed from socket io. (I think that is necessary to improve performance as long as io-uring is used for socket io, because rush_dispatch counterweigh all benefits brought by io-uring for socket only applications) It can be reproduced with the proxy benchmark on this branch: https://github.com/thirstycrow/glommio/tree/tcp_poll_recv_no_rush

**Comment by glommer** [comment]
The executor should not fall asleep if there are elements in the submission queue.
If it does, that's a bug.

**Comment by glommer** [comment]
It could be that we're just forgetting to check that criteria. But "sleep" means "there's no more work to possibly be done". if there are requests sitting in a queue, by definition there is work to do and we can't sleep.
