### ISSUE TITLE
Support restful API?

### ISSUE THREAD

**Issue by jim-king-2000** [DataDog/glommio#475]
Does glommio support writing restful API (web services)?

**Comment by glommer** [comment]
Glommio is just an executor. You likely want a library or framework to do that, and such library will need an executor of some sort.

Examples of such libraries are hyper, actix, etc. Currently those libraries are at the very least tokio-first, but some, like hyper, allow you to specify your own executor with some shim work.

Look for the file `examples/hyper.rs` on our examples directory to see how Hyper integration can be achieved.

**Comment by jim-king-2000** [comment]
So, any web framework which is based on glommio?
