### ISSUE TITLE
Add `alloc_dma_buffer` to `ExecutorProxy`

### ISSUE THREAD

**Issue by songzhi** [DataDog/glommio#481]
I see the source code is:
```rust
/// Allocates a buffer that is suitable for using to write to this file.
pub fn alloc_dma_buffer(&self, size: usize) -> DmaBuffer {
    self.file.reactor.upgrade().unwrap().alloc_dma_buffer(size)
}
```
I guess the `DmaBuffer` could be used across multiple `DmaFile`s as long as in the same `reactor`/`LocalExecutor`?
I think it's better to expose the API in the `LocalExecutor` level. So I can allocate a `DmaBuffer` and write it before openning a `DmaFile`.

**Comment by laa** [comment]
I suppose that is performance optimization and at the same time usage of metadata of the file to create DmaBuffer which is aligned with the page size of the file. The reactor uses a buddy allocator which quite fits there because of the usage of pow(2) sizes. You can use your own shared DmaBuffer allocated directly and align its size with the page of the file.   So IMHO API looks OK but probably @glommer has another opinion.

**Comment by songzhi** [comment]
Or maybe the DmaBuffer allocator could be exposed to let users create multiple allocators and allocate DmaBuffer any time they want. Of course it should be attatched to only one specific reactor.

**Comment by glommer** [comment]
Hello @songzhi ! I don't mind exposing this API at the reactor level. as @laa pointed out, it is useful, conceptually, to have access to it from the file object so we can perform alignment optimizations (which are currently not done), but that doesn't preclude exposing it at the reactor level.

Are you looking to contribute a PR for that? It would be awesome if you are, if not I will get to this shortly

**Comment by songzhi** [comment]
I'm glad to implement it.

**Comment by HippoBaro** [comment]
@songzhi that's alright, thanks for raising this! I'll make a patch soon.

**Comment by laa** [comment]
Hi guys, WDYT about exposing this method on `Local`(`Task`) level? If that is OK for you I will provide the PR soon because I need this method too.

**Comment by laa** [comment]
Fixed in PRs listed above.
