### ISSUE TITLE
RwLock panics inside implementation of Deref/DerefMut traits

### ISSUE THREAD

**Issue by laa** [DataDog/glommio#482]
According to the contract of Deref trait - "For similar reasons, this trait should never fail. Failure during dereferencing can be extremely confusing when Deref is invoked implicitly." https://doc.rust-lang.org/std/ops/trait.Deref.html
Because RwLockGuards fail inside of Deref implementation that probably should be fixed.

**Comment by glommer** [comment]
Thanks for pointing this out @laa!

Are you planning on providing a fix ? You don't have to, but that'd be cool. Just let us know for planning

**Comment by laa** [comment]
Hi @glommer .
Sure will provide a fix in a couple of weeks.

P.S. Glad to interact with you after a while  :-)

**Comment by laa** [comment]
Hi @glommer .
I have checked the code, I suppose we should panic on close. It will panic if readers/writers are still active. WDYT ?
I suppose better would be to return a result on close instead, but it will change the API of the library. IMHO this solution is better. 
WDYT ?

**Comment by glommer** [comment]
Either panic or close, or maybe return an error at close.
Users will then be forced to check it due to `must_check` rules and can retry, etc.

**Comment by bryandmc** [comment]
This is fixed by #510
