### ISSUE TITLE
AsyncWriter does not take into account situation when buffer is not completely written

### ISSUE THREAD

**Issue by laa** [DataDog/glommio#492]
According to the man write(2) `The number of bytes written may be less than count if, for example ... the call was interrupted by a signal handler  after having written less than count bytes.` 
If the reasons like reaching the limit of file size or not enough disk space are practically not so important but this one happens in real life. 
According to the code of the AsyncWriter: 
1. Every write-behind buffer is written up to the maximum limit. 
2. Once the buffer is full new fibre is forked and this fibre flushes the buffer.
3.. wait if all buffers are filled and flushed.

But code inside of forked fibre looks like:
```
 let flush_pos = self.current_pos();
        let handle = Local::local(async move {
            let res = file.write_at(buffer, aligned_pos).await;
            let mut state = state.borrow_mut();
            if !collect_error!(state, res) {
                state.flush_state.on_complete(flush_pos);
            }
            if let Some(waker) = state.waker.take() {
                drop(state);
                waker.wake();
            }
        })
        .detach();
```
So seems like the real amount of data written is ignored which can lead to problems.

**Comment by glommer** [comment]
To the best of my knowledge all of those situations will also return an error.
Keep in mind that C will return the error through `errno`, but for us that becomes an `Error`.
We `collect_error` and bail if that happens.

I am not aware of any situation that will have both a short write and and not return an error.

**Comment by laa** [comment]
Hm... I have seen myself when this (through Java call though) wrote only part of the data without any error reproted. Let us close this issue. I will try to reproduce the situation by test and in case of success, I will reopen it with a reproducer.
