### ISSUE TITLE
does thread per core means memory cannot be shared between the threads or does it mean it can?

### ISSUE THREAD

**Issue by hiqsociety** [DataDog/glommio#537]
does thread per core means memory cannot be shared between the threads or does it mean it can?

**Comment by glommer** [comment]
If you are never sharing memory, then you can just use different processes (which can be seen as an extreme version of thread-per-core). Think for example, a bunch of redis processes with manual sharding.

Thread-per-core allows for memory access between different threads through message passing. You have to be a bit careful for performance critical applications to free the memory in the same executors in which you allocated (to avoid incurring cross-CPU free), but passing things around is just fine.

**Comment by HippoBaro** [comment]
I am adding a bit more on this one to avoid any confusion. A TPC application is no different than any other process. You can create a global variable accessible by all threads, use mutexes, etc. 

However, that goes against the architectural ideas behind TPC. As Glauber said, it is preferable to codify ownership of resources in your application such that only a single CPU can ever access them. This allows maximal locality and no expensive cross-CPU communications. 

If you do need to share state, then passing messages via channels is the preferred way to do so. We provide channels in Glommio that make that easy to do. You can also use third-party channels like the ones provided by Tokio. 

There is a great saying from the creators of the Go language that captures the ideas at play here: ["Do not communicate by sharing memory; instead, share memory by communicating."](https://go.dev/blog/codelab-share)

I'll let you meditate on that! Feel free to drop on the Zulip if you have specific questions!
