### ISSUE TITLE
Failing to compile due to `membarrier-rs`

### ISSUE THREAD

**Issue by haixuanTao** [DataDog/glommio#557]
I am having this issue: https://github.com/jeehoonkang/membarrier-rs/issues/22 when I try to compile `glommio` on Linux and although I understand that this is not related to this crate I was wondering how are you guys compiling `glommio` 

Is there a `cargo` feature that allows you to bypass the by-default crate?

**Comment by glommer** [comment]
That's a tough one. As you noticed we opened a PR on that repository, and it never got anywhere.
The best way would be to stop using that crate and using something else instead, or do what we did with `iou` in the past, and license permitting, copying the code inside glommio and doing the fix ourselves.

**Comment by haixuanTao** [comment]
I see. As a user perspective, I feel like it is not necessarily easy to downcast Rust version just for one crate, and as a fix already exist, it's a shame the fix is not used. I don't know if there is any recommended way to fix unmaintained crates published on crates.io, but it happens quite often. 

Have you ever considered publishing a fixed `membarrier` with another name on crates.io?

**Comment by glommer** [comment]
I am not willing to push a new `membarrier`, because now I am stuck with the burden of maintaining it for general cases =p

We had a similar issue with `iou`, and what we did was we just imported the code (see `iou` directory inside glommio). 
What do you think of that ?

**Comment by haixuanTao** [comment]
Yeah completely understandable. I was thinking about putting a big warning in the README that says that you're not planning on maintaining it, but I guess that even for your own use, it might be tiring to maintain it. 

I feel that importing the code within glommio is a potential fix although it would lean toward the short term fix, and, other people who want to use your version of `membarrier` might not be able to do it. 

I guess something with a `git-submodule` would probably be a good balance between making the compilation work and letting the community build on top of your work if need be. But, I know that git-submodule tend to be harder to manage within git.

**Comment by glommer** [comment]
Can you tell me more about your environment ? I just compiled the current master with nightly and everything went just fine.

How did that fail for you ?

**Comment by haixuanTao** [comment]
I still have the issue compiling `membarrier==0.2.2` with latest from main branch:
```bash
   Compiling membarrier v0.2.2
   Compiling num-bigint v0.4.3
   Compiling num-iter v0.1.43
   Compiling num-rational v0.4.1
   Compiling rand v0.8.5
error[E0277]: `*mut c_void` cannot be sent between threads safely
   --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/membarrier-0.2.2/src/lib.rs:252:9
    |
252 | /         lazy_static! {
253 | |             /// An alternative solution to `sys_membarrier` that works on older Linux kernels and
254 | |             /// x86/x86-64 systems.
255 | |             static ref BARRIER: Barrier = {
...   |
291 | |             };
292 | |         }
    | |_________^ `*mut c_void` cannot be sent between threads safely
    |
    = help: within `Barrier`, the trait `Send` is not implemented for `*mut c_void`
note: required because it appears within the type `Barrier`
   --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/membarrier-0.2.2/src/lib.rs:207:16
    |
207 |         struct Barrier {
    |                ^^^^^^^
    = note: required because of the requirements on the impl of `Sync` for `spin::once::Once<Barrier>`
    = note: required because it appears within the type `Lazy<Barrier>`
    = note: shared static variables must have a type that implements `Sync`
    = note: this error originates in the macro `__lazy_static_create` (in Nightly builds, run with -Z macro-backtrace for more info)
``` 


The output of `uname -a` and `ulimit -l`.
```
Linux Carbon 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
65536
```

**Comment by glommer** [comment]
I submitted this:

https://github.com/DataDog/glommio/pull/558

We're having issues with the license verification stuff, but should fix that shortly
