### ISSUE TITLE
'Cannot allocate memory' warning when building a LocalExecutorBuilder

### ISSUE THREAD

**Issue by cjjb01** [DataDog/glommio#565]
Running this code
`
    let builder_unbound = LocalExecutorBuilder::new(Placement::Unbound);
    let _handle1 = builder_unbound.name("configuration").spawn(|| async move {
        watch_configuration(arc_config2);
    })?;`
Generates the following warning
`^[[2m2022-09-15T06:01:24.576196Z^[[0m ^[[33m WARN^[[0m ^[[2mglommio::sys::uring^[[0m^[[2m:^[[0m Error: registering buffers in the main ring. SkippingOs {
    code: 12,
    kind: OutOfMemory,
    message: "Cannot allocate memory",
}`

**Comment by HippoBaro** [comment]
Registering buffers with io_uring involves locking memory, which is governed by the limits of your system. By default, Linux is very restrictive, so we advise raising that limit is the readme file. 

Try to see what `ulimit -l` returns to see your current limit.

**Comment by cjjb01** [comment]
Thanks for the reply, I did increase the limit:
marea@ubuntu:~/projects/streamer$ ulimit -l
131072

**Comment by HippoBaro** [comment]
Can you share with us the way you are spawning the executor? Specifically, are you using the `io_memory` configuration?

**Comment by cjjb01** [comment]
Never mind, I increased the memory settings to the following and the error has disappeared:
`*    hard    memlock        1048576`
`*    soft    memlock        1048576`

Thank you very much for your prompt responses to my questions! Have a great weekend!

**Comment by HippoBaro** [comment]
Awesome! It's likely because the default io memory we try to allocate exceeded the limit you set. This is unlikely to happen for a single executor, but when building a pool, we tend to reach the limit much faster, especially on a bigger system. 

Happy your problem is resolved. Take care!
