### ISSUE TITLE
possible typo in ping_pong example

### ISSUE THREAD

**Issue by viktortnk** [DataDog/glommio#566]
https://github.com/DataDog/glommio/blob/6e5eae03727ae8a3f79d5ba01126de484ebc19ce/examples/ping_pong.rs#L23

Should it be set to false in this line (curently true)?

I assume the intention is to allow jumping between coroutines

**Comment by glommer** [comment]
The main goal of this example is to demonstrate `enclose!` in a real application. But obviously we want the code to be sound.

Reading the code, you are correct. The first loop should test for true and set to false, and the second loop should do the opposite.
