### ISSUE TITLE
Extend read ownership of `DmaBuffer` past `write_to`

### ISSUE THREAD

**Issue by vlovich** [DataDog/glommio#575]
I had this thought that it would be really convenient to be able to continue doing some kind of background processing of the data buffer in a background thread (e.g. converting it into a more optimal data structure) while I/O is ongoing without requiring a copy. I'm not too familiar with how io_uring works so maybe this isn't possible, but would it make sense to try to offer the ability to extend the read lifetime of a `DmaBuffer` by creating a `ReadReference` which would preclude that buffer being reused for allocation until it's dropped? Happy to try to work on this if you think it's possible & would welcome a contribution along these lines.

**Comment by glommer** [comment]
I think it is possible, but would require a different API.

This needs more thought to make sure the API is sane, we wouldn't be able to do this by just adding stuff on top of `write`. But it is something that other people had requested in the past, and I think it is reasonable.

This seems to me mostly a rust issue, not an io_uring issue. io_uring will write whatever pointer you give it. The biggest question is how to derive an API in which buffers are safely shared on the rust side. The buffer needs to be writeable up to a point, but then after you pass it down to write, it needs to be read only. It also has to be safe enough so it is not dropped until the kernel returns, and handle cancellations.

IOW, totally possible, just need a really sane API.

**Comment by vlovich** [comment]
I figured it was going to be a Rust thing. The only concern I had was that submitting an io_uring buffer passed off ownership of the buffer to the kernel. My perhaps naiive idea (I'm very new to Rust), is to basically just have:

```
impl DmaBuffer {
  fn seal(self) -> SealedDmaBuffer { ... }
}
```

Then all `write` methods can be changed to require taking a `SealedDmaBuffer`. A `SealedDmaBuffer` is clonable and acts like a `ReadResult`. Each `SealedDmaBuffer` holds a non-atomic reference counter that prevents that buffer from getting reused.
