### ISSUE TITLE
User-space TCP/IP stack? 

### ISSUE THREAD

**Issue by playXE** [DataDog/glommio#588]
Is there any plans for having user-space TCP/IP stack in glommio? Like smoltcp or some built on top of DPDK?

**Comment by glommer** [comment]
No plans. In fact I had very bad experiences with DPDK in the past. TCP is incredibly difficult, it's a humongous amount of work, and you're likely to still be behind Linux anyway, plus now a plethora of bugs and corner cases.

**Comment by playXE** [comment]
> No plans. In fact I had very bad experiences with DPDK in the past. TCP is incredibly difficult, it's a humongous amount of work, and you're likely to still be behind Linux anyway, plus now a plethora of bugs and corner cases.

Thanks for answer! I am having bad experience with setting up DPDK on AWS manually right now so that's why I asked. :) 

Guess we'll just use glommio's net stack.
