### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by brianshih1** [DataDog/glommio#599]
Hello! I am trying to run Glommio on my macOS but I run into: `fatal error: 'linux/fs.h' file not found` error. I'm trying to find instructions for Glommio to run on macOS but can't seem to find it. I assume Glommio doesn't run on MacOS?

I use an Apple M1 Pro and running on macOS 13.4. Here is the entire error log:

  --- stdout
  TARGET = Some("aarch64-apple-darwin")
  OPT_LEVEL = Some("0")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-arch" "arm64" "-I" "/Users/brian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glommio-0.8.0/liburing/src/include" "-I" "/Users/brian/Desktop/distributed_system/test_glommio/target/debug/build/glommio-56b7a9ca1469bcc4/out/src/include" "-Wall" "-o" "/Users/brian/Desktop/distributed_system/test_glommio/target/debug/build/glommio-56b7a9ca1469bcc4/out/8fe85c871eb7ebac-setup.o" "-c" "/Users/brian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glommio-0.8.0/liburing/src/setup.c"
  cargo:warning=In file included from /Users/brian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glommio-0.8.0/liburing/src/setup.c:14:
  cargo:warning=/Users/brian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glommio-0.8.0/liburing/src/include/liburing/io_uring.h:11:10: fatal error: 'linux/fs.h' file not found

**Comment by glommer** [comment]
Sorry it took me a while to get to this.

Indeed glommio at the moment does not run on MacOS.
