### ISSUE TITLE
Adding poll_readable / poll_writeable to Datagram

### ISSUE THREAD

**Issue by vlovich** [DataDog/glommio#609]
I was hoping to integrate glommio as a backend for Quinn. To do so, I believe I need to implement poll_readable / poll_writeable.

As part of this, I think I need to move the Timeout implementation that's used in stream.rs into a shareable spot so that datagram.rs can replace it's timers with that. As part of that refactor, I'm thinking that instead of Timeout containing Cell<Option>, it is given a reactor in `new` and is responsible for registering. The parent would then hold the timer as Cell<Option<Timeout>>.

My thinking on the datagram side of things is that the implementation would be largely similar to what's in stream.rs. The main distinction is that unlike AsyncRead / AsyncWrite which takes a buffer for poll_read / poll_write, poll_readable / poll_writable just take the Context and no buffer since the model is that Quinn waits for the socket to be readable and then runs its internal state logic.

Are there any problems with this approach / any potential footguns to watch out for?

I've started an issue tracking the changes I think I'll need to make to quinn to support that as I think it requires Send+Sync to be implemented for the underlying Runtime & that's not compatible with Glommio. https://github.com/quinn-rs/quinn/issues/1681

**Comment by glommer** [comment]
I am not familiar with Quinn and what HTTP/3 will expect.

The direction you propose seems ok, and I'm curious to see how the numbers would look like.
