### ISSUE TITLE
Shares example is flipped?

### ISSUE THREAD

**Issue by vlovich** [DataDog/glommio#615]
> This example creates two task queues: tq1 has 2 shares, tq2 has 1 share. This means that if both want to use the CPU to its maximum, tq1 will have 1/3 of the CPU time (1 / (1 + 2)) and tq2 will have 2/3 of the CPU time

But if tq1 is created with 2 shares, isn't it supposed to get 2/3 of the CPU time?

**Comment by glommer** [comment]
yes, the comment is flipped. I'll fix it.

Thanks!
