### ISSUE TITLE
Ordering of `ReadManyResult `

### ISSUE THREAD

**Issue by ozgrakkurt** [DataDog/glommio#632]
Hello!! Thank you for creating this library

Does the result of `ImmutableFile::read_many` has the same ordering as the `iovs` argument? I couldn't find it in docs. From looking at the code it seems like it is ordered but couldn't be sure about it.

Also happy to add this to docs.

**Comment by glommer** [comment]
I/Os are guaranteed to be initiated in order, but there is no guarantee that they will complete in order.
I believe the current implementation does complete them in order, though, but it is usually easier to achieve better performance if ordering guarantees can be broken, so I'd prefer not to provide this guarantee.

**Comment by ozgrakkurt** [comment]
> I/Os are guaranteed to be initiated in order, but there is no guarantee that they will complete in order. I believe the current implementation does complete them in order, though, but it is usually easier to achieve better performance if ordering guarantees can be broken, so I'd prefer not to provide this guarantee.

thanks! Makes a lot of sense about the ordering, also applies to all of my usecases
