### ISSUE TITLE
Is it possible to make a release?

### ISSUE THREAD

**Issue by ozgrakkurt** [DataDog/glommio#642]
Hello!

Is it possible to make a release to crates.io?

I am using glommio as a dependency in one of my libraries but I can't release a version that depends on git version of glommio.

I'll just fork and release under a different name for temporary fix but it would be nice to also get a release

**Comment by glommer** [comment]
I am planning to make a release in about 2 weeks.
@vlovich anything that you'd like to see in that is not already merged?

**Comment by vlovich** [comment]
Thanks for asking but good thing I happened to peruse the issues backlog. I don't have any pending PRs at the moment :).

**Comment by glommer** [comment]
Just released v0.9.0
