### ISSUE TITLE
Implement `Send + Sync` for `ReadResult`

### ISSUE THREAD

**Issue by ozgrakkurt** [DataDog/glommio#667]
This might be useful in a case like this:

- Make a huge reads like 4-6 MB in a stream
- Offload decoding of data to other threads so it can run in parallel

If we copy 4MB of data, unless we are using pre-allocated huge pages in the application it causes massive amount of page faults and is a big bottleneck.

**Comment by glommer** [comment]
Being Send + Sync means that now you have two threads manipulating that data.
If you pass ownership, than you can still pass it.

If you really want to be manipulating the same buffer in multiple threads, in the general case, that is unsafe. You can guarantee its safety by wrapping this in its own api, but that doesn't mean the general purpose api should be send + sync.
