### ISSUE TITLE
Merge read requests for random file access

### ISSUE THREAD

**Issue by glommer** [DataDog/glommio#73]
Although a fully fledged I/O Scheduler is probably way into the future, there is a functionality that I would like to see from an early implementation that can serve as a seed for that: random read request merging.

Imagine a read workload for a datastore. It is possible, if not likely, that many independent readers may be touching the same file, in the same - or close enough - position.

If that is the case, we don't have to go to storage and every time.
In preparation for such a change, in PR https://github.com/DataDog/scipio/pull/72 I am changing the return of `read_dma` and `read_dma_aligned` to be a `ReadResult` instead of a `DmaBuffer`. The `ReadResult` encapsulates a buffer, and two or more reads that end up reading from the same buffer may reuse them.

If reads are queued from positions similar to the one we are reading from (either adjacent or within a tolerance gap), we can extend the reads. For example: 

Let's say we fire read for position 0 for file A, reading 512 bytes.
Then another reader tries to read, 1024 bytes from position 1024.

We shouldn't ever delay firing the reads waiting for possible merges: but let's say when the time comes to fire the I/O, we see that those two requests are in the queue: it is better to read 2048 bytes and just give each one a slice of the buffer.

**Comment by zserik** [comment]
As a first step, we should align read requests, and if then two requests are exactly the same, we should merge them into one, which returns the result to two requests with different wakers... This requires the functionality to distribute request responses.

**Comment by laa** [comment]
Hi @glommer , what do you think is close enough in this case? The first assumption could be that close enough means one-page size. But still, file storage is slower than memory, I would say that distance of four pages (by default with the ability to change by the user) between requests could be close enough. WDYT?

**Comment by glommer** [comment]
This will vary from device to device. Usually if you consider a 4kB page, if something is in the next page it might still be worth grabbing. So I'd say 8kB is a decent initial distance.

**Comment by laa** [comment]
@glommer I suppose would be better to measure in pages, not in Kb. WDYT? In such terminology near enough is 2 pages. I suppose thinking in pages is better because 1-page distance always will be close enough.

**Comment by glommer** [comment]
pages is an OS / memory concept. It doesn't necessarily translate to device properties.
There are devices for which larger transfers will be better, and there are devices which are okay with smaller transfers
(you can estimate that by dividing the peak bandwidth of the device by the peak iops)

**Comment by laa** [comment]
I mean the size of the device page, you can not read less than the size of the device page. So 1 page is close enough. Sure we can not say that all two reads are read from the single page but that is a reasonable assumption. Or did I miss something?

**Comment by laa** [comment]
We already have a notion of the page in DMA file, is not reasonable to extend it for this feature too ?

**Comment by laa** [comment]
After some time of thinking probably I got what you mean. Probably the distance in bytes would be better.

**Comment by HippoBaro** [comment]
I recently got #341 merged and it partially solves this issue by coalescing read requests when reading many iovecs from a file. Admittedly, it doesn't deduplicate/merge across tasks yet, which is what we really want, but it's a start.
